# Generated by Django 4.1.5 on 2023-02-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='words_count',
            field=models.IntegerField(null=True),
        ),
    ]
